---
title: "Projekt 1"
output: html_document
date: "2022-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0. Preprocessing

#### 0.0 Importing libraries

```{r}
library(ggplot2)
library(glue)
library(dplyr)
library(readr)
library(ggthemes)
```

#### 0.1 Importing data

```{r}
inflation_data <- read.csv("data/EU_Inflation_HICP_data_mod.csv", header = TRUE, sep = ",")
deposits_data <- read.csv("data/EU_deposits_1yr_data_mod.csv", header = TRUE, sep = ",")
```

#### 0.2 Converting date

```{r}
inflation_data$Period <- as.Date(inflation_data$Period, format = "%d/%m/%Y")
deposits_data$Period <- as.Date(deposits_data$Period, format = "%d/%m/%Y")
```

#### 0.3 Converting to numeric

```{r}
deposits_data[, 2:34] <- sapply(deposits_data[, 2:34], as.numeric)
str(deposits_data)
```

## 1. Exercise 1

#### 1.1

###### 1.1.1 Creating subsets
```{r}
eurozone_countries_inflation <- select(inflation_data, matches("Period|Austria|Belgium|Cyprus|Germany|Estonia|Spain|Finland|France|Greece|Ireland|Italy|Lithuania|Luxembourg|Latvia|Malta|Netherlands|Portugal|Slovenia|Slovakia"))
other_countries_inflation <- select(inflation_data, !matches("EU|Austria|Belgium|Cyprus|Germany|Estonia|Spain|Finland|France|Greece|Ireland|Italy|Lithuania|Luxembourg|Latvia|Malta|Netherlands|Portugal|Slovenia|Slovakia"))
# EU_countries_inflation <- select(inflation_data, matches("Period|EU"))
# Poland_inflation <- select(inflation_data, matches("Period|Poland"))

head(eurozone_countries_inflation)
head(other_countries_inflation)
# head(EU_countries_inflation)
# head(Poland_inflation)
```


```{r}
eurozone_countries_inflation_avg <- data.frame(eurozone_countries_inflation[1], (rowMeans(eurozone_countries_inflation[2:20], na.rm=TRUE)))
other_countries_inflation_avg <- data.frame(other_countries_inflation[1], (rowMeans(other_countries_inflation[2:9], na.rm=TRUE)))
EU_countries_inflation <- data.frame(eurozone_countries_inflation[1], select(inflation_data, matches("EU")))
Poland_inflation <- data.frame(eurozone_countries_inflation[1], select(inflation_data, matches("Poland")))
```


```{r}
inflation_avg <- data.frame(eurozone_countries_inflation[1], eurozone_countries_inflation_avg[2], other_countries_inflation_avg[2], EU_countries_inflation[2], Poland_inflation[2])

colnames(inflation_avg)[1] <- "Period"
colnames(inflation_avg)[2] <- "Eurozone"
colnames(inflation_avg)[3] <- "Other"
colnames(inflation_avg)[4] <- "EU"
colnames(inflation_avg)[5] <- "Poland"
```


###### 1.1.2 Inflation rate plot

```{r}
ggplot(data = inflation_avg, aes(x=Period)) +
  geom_line( aes(y=Eurozone), color="#0072BD", size=1.5)+
  geom_line( aes(y=Other), color="#77AC30", size=1.5)+
  geom_line( aes(y=EU), color="#4DBEEE", size=1.5)+
  geom_line( aes(y=Poland), color="#A2142F", size=1.5)+
  labs(title = "Inflation rate")
```















#### 1.2

###### 1.2.1 Creating subsets

```{r}
eurozone_countries_deposits <- select(deposits_data, matches("Euro|Period"))
other_countries_deposits <- select(deposits_data, !contains("Euro"))
head(eurozone_countries_deposits)
head(other_countries_deposits)
```



```{r}
eurozone_countries_deposits_avg <- data.frame(eurozone_countries_deposits[1], rowMeans(eurozone_countries_deposits[2:20], na.rm=TRUE))
other_countries_deposits_avg <- data.frame(other_countries_deposits[1], rowMeans(other_countries_deposits[2:15], na.rm=TRUE))
```







#### 1.3

```{r}
country <- "Estonia"

ggplot(data = inflation_data, aes(x = Period, y = inflation_data[ , country])) +
  geom_bar(stat = "identity", fill = "purple") +
  labs(title = glue("Inflation in {country}"),
       x = "Date", y = "Inflation rate")
```


